### ISSUE TITLE
ValueError: VectorTown.proto:1405:16: Expected field name.

### ISSUE THREAD

**Issue by Luvata** [marin-m/pbtk#12]
Last Wednesday I still can use `pbtk` to fiddling with google maps's protobuf (step 1 and step 3)
But then on Friday I got ValueError on most of endpoints on step 3:
Only two of them still works 
```
/maps/@{coods}/data={data}
/maps/dir/{dir1}/{dir2}/@{cỏods}/data={data}
```

My error with `/s`
```
Traceback (most recent call last):
  File "gui.py", line 310, in launch_fuzzer
    self.pb_request = dict(self.pb_request)[data['request']['proto_msg']]()
  File "/home/thanhlv/workspace/decode_pb/pbtk/utils/common.py", line 179, in load_proto_msgs
    raise ValueError(cmd.stderr.decode('utf8'))
ValueError: Search.proto:1884:62: Field numbers must be positive integers.
Search.proto:636:18: "undefined" is not defined.
Search.proto:637:18: "undefined" is not defined.
Search.proto:638:29: Field number 6 has already been used in "Search.E" by field "f".
Search.proto:639:18: "undefined" is not defined.
Search.proto:640:18: Field number 8 has already been used in "Search.E" by field "h".
Search.proto:641:20: Field number 9 has already been used in "Search.E" by field "i".
Search.proto:828:22: "undefined" is not defined.
Search.proto:1879:50: "undefined" is not defined.
Search.proto:1880:50: "undefined" is not defined.
Search.proto:1883:41: "undefined" is not defined.
Search.proto:2011:14: "undefined" is not defined.
Search.proto:2013:5: "undefined" is not defined.
Aborted (core dumped)
```

and `/maps/vt`
```
Traceback (most recent call last):
  File "gui.py", line 310, in launch_fuzzer
    self.pb_request = dict(self.pb_request)[data['request']['proto_msg']]()
  File "/home/thanhlv/workspace/decode_pb/pbtk/utils/common.py", line 179, in load_proto_msgs
    raise ValueError(cmd.stderr.decode('utf8'))
ValueError: VectorTown.proto:1405:16: Expected field name.
Aborted (core dumped)
```

Is it only my problem or did Google recently change the response format ?  

Thanks for your awesome tool, it helps me a lot !

**Comment by Luvata** [comment]
I add this line 
```js
var type = typeArray[field_letter];
>> if (type === undefined) {console.log(">>>> WARNING ", field_letter)};
```
And start step 1, when open dev tools I found 4 new types are 
```
c
l (lower case of L)
+
_
```

**Comment by exhumea** [comment]
In addition to the ones you've already listed, I also spotted those new custom _types_:
```
^
*
,  // seems to be for used for packed repeated scalar types
```
