### ISSUE TITLE
Error on start of the program

### ISSUE THREAD

**Issue by xtauck** [marin-m/pbtk#13]
This is what I get, any suggestions? All the dependencies are installed

`kali@kali:~/pbtk$ ./gui.py 
Traceback (most recent call last):
  File "./gui.py", line 20, in <module>
    from views.fuzzer import ProtobufItem, ProtocolDataItem
  File "/home/kali/pbtk/views/fuzzer.py", line 5, in <module>
    from PyQt5.QtWebEngineWidgets import QWebEngineView
ImportError: libQt5WebEngineWidgets.so.5: cannot open shared object file: No such file or directory`

**Comment by marin-m** [comment]
Hello,

Have you tried installing this package? If no, does it solve the issue?

```
sudo apt install libqt5webenginewidgets5
```

**Comment by xtauck** [comment]
I installed the package you suggested and I got another error when trying to run it

`root@kali:/home/kali/pbtk# ./gui.py 
Traceback (most recent call last):
  File "./gui.py", line 20, in <module>
    from views.fuzzer import ProtobufItem, ProtocolDataItem
  File "/home/kali/pbtk/views/fuzzer.py", line 5, in <module>
    from PyQt5.QtWebEngineWidgets import QWebEngineView
ImportError: /lib/x86_64-linux-gnu/libQt5Core.so.5: version` `Qt_5.15' not found (required by /usr/local/lib/python3.8/dist-packages/PyQt5/QtWebEngineWidgets.abi3.so)`

**Comment by marin-m** [comment]
Maybe that you could try to run this command:

```bash
sudo apt install python3-pyqt5.qtwebengine python3-pyqt5
```

And, if it does not still work, uninstalling the local PyQt install,

```bash
sudo pip3 uninstall pyqt5 pyqtwebengine
```

Could you tell whether it solves the issue?

Thanks,

**Comment by xtauck** [comment]
the first command seems to have fixed it, I'll try it a bit I hope now it's all ok.
Thanks!
