### ISSUE TITLE
Using decompiled data as intput

### ISSUE THREAD

**Issue by demiantres** [marin-m/pbtk#14]
Hi,

I have already decompiled a jar binary using fernflower and other tools because it fails with JAD. Is it somehow possible to use these decompiled files as input for .proto generation?

Thanks.

**Comment by marin-m** [comment]
Hello,

I fear that not, this tool has been quite specially crafted to parse JAD output (because it showed to decompile the most classes or fail to decompile the less functions, even imperfectly, during my tests) and other decompiling tools will produce other patterns.

Is JAD failing to run because you're using a recent macOS version, thoroughly failing to decompile code because some incompatibility, or not working because another reason?

**Comment by demiantres** [comment]
The JAD decompilation process hangs with an exception:

```
dan@ubuntu:~/Desktop/proto/pbtk$ ./gui.py 
./gui.py:442: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  view.move((resolution.width() / 2) - (view.frameSize().width() / 2),
./gui.py:133: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  self.view.setValue(progress * 100)

In com.google.protobuf.nano.InternalNano:

In com.google.protobuf.nano.MessageNano:

In com.google.protobuf.nano.ExtendableMessageNano:

In c.g.b.a.a.a0:

In c.g.b.a.a.a1:

In c.g.b.a.a.a2:

In c.g.b.a.a.a3:
Error: Jad annotation couldn't be parsed: 'StringBuilder(50)' / c.g.b.a.a.a4 / [('java.lang.StringBuilder', 'java.lang.StringBuilder', 'append', 'int'), ('java.lang.StringBuilder', 'java.lang.StringBuilder', 'append', 'java.lang.String'), ('java.lang.String', 'java.lang.StringBuilder', 'toString', ''), ('java.lang.Integer', 'java.lang.Integer', 'valueOf', 'int'), ('void', 'com.google.protobuf.nano.CodedInputByteBufferNano', 'rewindToPosition', 'int'), ('boolean', 'com.google.protobuf.nano.ExtendableMessageNano', 'storeUnknownField', 'com.google.protobuf.nano.CodedInputByteBufferNano, int'), ('int', 'java.lang.Integer', 'intValue', ''), ('void', 'com.google.protobuf.nano.CodedOutputByteBufferNano', 'writeInt32', 'int, int'), ('long', 'java.lang.Long', 'longValue', ''), ('void', 'com.google.protobuf.nano.CodedOutputByteBufferNano', 'writeInt64', 'int, long'), ('void', 'com.google.protobuf.nano.CodedOutputByteBufferNano', 'writeString', 'int, java.lang.String'), ('void', 'com.google.protobuf.nano.CodedOutputByteBufferNano', 'writeMessage', 'int, com.google.protobuf.nano.MessageNano'), ('void', 'com.google.protobuf.nano.CodedOutputByteBufferNano', 'writeMessage', 'int, com.google.protobuf.nano.MessageNano'), ('void', 'com.google.protobuf.nano.CodedOutputByteBufferNano', 'writeMessage', 'int, com.google.protobuf.nano.MessageNano'), ('void', 'com.google.protobuf.nano.ExtendableMessageNano', 'writeTo', 'com.google.protobuf.nano.CodedOutputByteBufferNano')]
Traceback (most recent call last):
  File "./gui.py", line 462, in run
    for name, contents in self.extractor['func'](input_):
  File "/home/dan/Desktop/proto/pbtk/extractors/jar_extract.py", line 236, in handle_jar
    extract_lite(jar, cls, enums, gen_classes_nodollar, codedinputstream, codedoutputstream, map_entry_cls, out_additional_cls,
  File "/home/dan/Desktop/proto/pbtk/extractors/jar_extract.py", line 261, in extract_lite
    code = jar.decomp(cls)
  File "/home/dan/Desktop/proto/pbtk/utils/java_wrapper.py", line 70, in decomp
    self.decompiled[cls] = ClassWrapper(cls, self)
  File "/home/dan/Desktop/proto/pbtk/utils/java_wrapper.py", line 229, in __init__
    call_sig = self.prototype_from_annote(name, args)
  File "/home/dan/Desktop/proto/pbtk/utils/java_wrapper.py", line 273, in prototype_from_annote
    raise ValueError
ValueError

```

**Comment by demiantres** [comment]
Here are the classes: https://gofile.io/d/6FlfC2

**Comment by marin-m** [comment]
Hello,

The "`c.g.b.a.a.a4`" class doesn't seem to be included in the .JAR file you shared but anyway I pushed a potential fix as commit 6d54e13. Does it work better?

**Comment by demiantres** [comment]
Thanks it works much better now 👍.

**Comment by demiantres** [comment]
Interestingly most proto classes are not found.
