### ISSUE TITLE
FileNotFoundError classes-dex2jar.jar

### ISSUE THREAD

**Issue by UnknowUsername** [marin-m/pbtk#23]
PS C:\Users\misti\Desktop\Begin\PrivacySecurityReversProtection\revers\pbtk-1.0.5> ./gui.py
C:\Users\misti\Desktop\Begin\PrivacySecurityReversProtection\revers\pbtk-1.0.5\gui.py:442: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be 
removed in a future version of Python.
  view.move((resolution.width() / 2) - (view.frameSize().width() / 2),
Traceback (most recent call last):
  File "C:\Users\misti\Desktop\Begin\PrivacySecurityReversProtection\revers\pbtk-1.0.5\gui.py", line 462, in run
    for name, contents in self.extractor['func'](input_):
  File "C:\Users\misti\Desktop\Begin\PrivacySecurityReversProtection\revers\pbtk-1.0.5\extractors\jar_extract.py", line 51, in handle_jar
    with JarWrapper(path) as jar:
  File "C:\Users\misti\Desktop\Begin\PrivacySecurityReversProtection\revers\pbtk-1.0.5\utils\java_wrapper.py", line 25, in __init__      
    self.handle_file(fname)
  File "C:\Users\misti\Desktop\Begin\PrivacySecurityReversProtection\revers\pbtk-1.0.5\utils\java_wrapper.py", line 43, in handle_file   
    self.handle_file(self.name + '/' + cls)
  File "C:\Users\misti\Desktop\Begin\PrivacySecurityReversProtection\revers\pbtk-1.0.5\utils\java_wrapper.py", line 34, in handle_file   
    with ZipFile(fname) as jar:
  File "C:\Python\Python38\lib\zipfile.py", line 1251, in __init__
    self.fp = io.open(file, filemode)
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\misti\\AppData\\Local\\Temp\\tmpkxi_mopf/classes-dex2jar.jar'  ****

**Comment by erob8** [comment]
Yeah I'm getting this same error on Windows when i use the jar_extract with an apk file. 
Linux works fine.

**Comment by UnknowUsername** [comment]
Hey, from where did U find my mail?

Sent from [ProtonMail](https://protonmail.ch), encrypted email based in Switzerland.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by MrNadimi** [comment]
Same error on Ubuntu.

**Comment by MrNadimi** [comment]
I got the solution ( it worked on all system operations )

* Downloading the latest release of [DexPatcher](https://github.com/DexPatcher/dex2jar) and unzip that
* Delete all files and folders from  **pbtk/utils/external/dex2jar** directory and  Replace  all files and folders from **dex-tools-2.1-20190905-lanchon  (unziped DexPatcher folder)**  to  **pbtk/utils/external/dex2jar** directory  

This method will definitely solve the problem
Regards.

**Comment by nref** [comment]
This happens on Linux, Windows, and WSL2, and the method given by @Nadimibox did not fix it.

**Comment by nref** [comment]
Ran `dex2jar` manually and saw this exception which is suppressed by `subprocess.run`:

```bash
com.googlecode.d2j.DexException: not support version.
        at com.googlecode.d2j.reader.DexFileReader.<init>(DexFileReader.java:151)
        at com.googlecode.d2j.reader.DexFileReader.<init>(DexFileReader.java:211)
        at com.googlecode.dex2jar.tools.Dex2jarCmd.doCommandLine(Dex2jarCmd.java:104)
        at com.googlecode.dex2jar.tools.BaseCmd.doMain(BaseCmd.java:288)
        at com.googlecode.dex2jar.tools.Dex2jarCmd.main(Dex2jarCmd.java:32)
```

2.1 is pretty old by now. Using the [latest version](https://github.com/pxb1988/dex2jar/releases/tag/v2.4) worked.

I patched `JarWrapper.handle_file` to bail if `dex2jar` fails:

```python
        with open(fname, 'rb') as fd:
            if fd.read(4) == b'dex\n':
                new_jar = self.name + '/classes-dex2jar.jar'
                r = run([dex2jar, fname, '-f', '-o', new_jar], cwd=self.name, capture_output=True)

                stderr = r.stderr.decode()
                if len(stderr) > 0:
                    print("dex2jar failed: ", r.stderr.decode())
                    return
                fname = new_jar
```

**Comment by marin-m** [comment]
Fork changes merged in 1.1.2, thanks
