### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by lol-1-afk** [marin-m/pbtk#28]
Traceback (most recent call last):
  File "C:\main\soft\protobuf\pbtk-master\gui.py", line 462, in run
    for name, contents in self.extractor['func'](input_):
  File "C:\main\soft\protobuf\pbtk-master\extractors\jar_extract.py", line 51, in handle_jar
    with JarWrapper(path) as jar:
  File "C:\main\soft\protobuf\pbtk-master\utils\java_wrapper.py", line 25, in __init__
    self.handle_file(fname)
  File "C:\main\soft\protobuf\pbtk-master\utils\java_wrapper.py", line 46, in handle_file
    self.bonus_protos[cls] = jar.read(cls).decode('utf8')
**UnicodeDecodeError: 'utf-8' codec can't decode byte 0x86 in position 5: invalid start byte**

APK: com.google.android.gm_2023.04.02.523594694.release_63820521.apk (https://trashbox.ru/files30/1792705/com.google.android.gm_2023.04.02.523594694.release_63820521.apk/)

**Comment by rom4ster** [comment]
Im having the same error. Is there any word on this?

**Comment by bulutg** [comment]
Traceback (most recent call last):
  File "/home/bulut/pbtk/extractors/./jar_extract.py", line 962, in <module>
    extractor_main('jar_extract')
  File "/home/bulut/pbtk/extractors/../utils/common.py", line 261, in extractor_main
    nb_written, wrote_endpoints = extractor_save(args.output_dir, '', extractor['func'](args.input_))
  File "/home/bulut/pbtk/extractors/../utils/common.py", line 217, in extractor_save
    for name, contents in outputs:
  File "/home/bulut/pbtk/extractors/./jar_extract.py", line 51, in handle_jar
    with JarWrapper(path) as jar:
  File "/home/bulut/pbtk/extractors/../utils/java_wrapper.py", line 25, in __init__
    self.handle_file(fname)
  File "/home/bulut/pbtk/extractors/../utils/java_wrapper.py", line 46, in handle_file
    self.bonus_protos[cls] = jar.read(cls).decode('utf8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf7 in position 5: invalid start byte


Same...
