### ISSUE TITLE
TypeError: unhashable type: 'RepeatedScalarFieldContainer'

### ISSUE THREAD

**Issue by dmiller423** [marin-m/pbtk#30]
Scanning elf containing obvious protobuf's
```
Traceback (most recent call last):
  File "c:\path_to\pbtk\gui.py", line 462, in run
    for name, contents in self.extractor['func'](input_):
  File "c:\path_to\pbtk\extractors\from_binary.py", line 78, in walk_binary
    yield descpb_to_proto(proto)
          ^^^^^^^^^^^^^^^^^^^^^^
  File "c:\path_to\pbtk\utils\descpb_to_proto.py", line 45, in descpb_to_proto
    out += parse_msg(desc, scopes, desc.syntax).strip('\n')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\path_to\pbtk\utils\descpb_to_proto.py", line 60, in parse_msg
    blocks[nested_msg.name] = parse_msg(nested_msg, scopes, syntax)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\path_to\pbtk\utils\descpb_to_proto.py", line 79, in parse_msg
    out += fmt_field(field, scopes, blocks, syntax)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\path_to\pbtk\utils\descpb_to_proto.py", line 168, in fmt_field
    line = '%s %s %s = %s;\n' % (labels[field.label], type_, field.name, fmt_value(field.number, field.options, optarr=default))
                                                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\path_to\pbtk\utils\descpb_to_proto.py", line 126, in fmt_value
    opts.append('%s = %s' % (option.name, fmt_value(value, desc=option)))
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\path_to\pbtk\utils\descpb_to_proto.py", line 118, in fmt_value
    val = desc.enum_type.values_by_number[val].name
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
TypeError: unhashable type: 'RepeatedScalarFieldContainer'
```

**Comment by Davis-3450** [comment]
I got the same issue

**Comment by dmiller423** [comment]
It doesn't support many types of fields, but you'd think scalars would be simple ... basically an array of integers would be a 'RepeatedScalar' Field ?  who knows I used protodump and it worked w.o any hassle

**Comment by Davis-3450** [comment]
Little update if that works for you or anyone else.

One month ago, I found a fix, but I forgot to share it, here's [my fork](https://github.com/Davis-3450/pbtk/blob/master/utils/descpb_to_proto.py) this worked for the error that I got which was very similar if not the same, it's based on [this](url) which fixed this issue: #23

**Comment by marin-m** [comment]
Fork changes merged in 1.1.2, thanks

**Comment by drobotk** [comment]
Seems like I have a similar issue on 1.1.2

```
Traceback (most recent call last):
  File "/snap/pbtk/34/bin/pbtk-from-binary", line 6, in <module>
    sys.exit(main())
             ^^^^^^
  File "/snap/pbtk/34/lib/python3.12/site-packages/pbtk/extractors/from_binary.py", line 88, in main
    extractor_main('from_binary')
  File "/snap/pbtk/34/lib/python3.12/site-packages/pbtk/utils/common.py", line 336, in extractor_main
    nb_written, wrote_endpoints = extractor_save(
                                  ^^^^^^^^^^^^^^^
  File "/snap/pbtk/34/lib/python3.12/site-packages/pbtk/utils/common.py", line 280, in extractor_save
    for name, contents in outputs:
  File "/snap/pbtk/34/lib/python3.12/site-packages/pbtk/extractors/from_binary.py", line 82, in walk_binary
    yield descpb_to_proto(proto)
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/snap/pbtk/34/lib/python3.12/site-packages/pbtk/utils/descpb_to_proto.py", line 51, in descpb_to_proto
    out += parse_msg(desc, scopes, desc.syntax).strip('\n')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/snap/pbtk/34/lib/python3.12/site-packages/pbtk/utils/descpb_to_proto.py", line 67, in parse_msg
    blocks[nested_msg.name] = parse_msg(nested_msg, scopes, syntax)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/snap/pbtk/34/lib/python3.12/site-packages/pbtk/utils/descpb_to_proto.py", line 90, in parse_msg
    out += fmt_field(field, scopes, blocks, syntax)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/snap/pbtk/34/lib/python3.12/site-packages/pbtk/utils/descpb_to_proto.py", line 208, in fmt_field
    fmt_value(field.number, field.options, optarr=default),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/snap/pbtk/34/lib/python3.12/site-packages/pbtk/utils/descpb_to_proto.py", line 146, in fmt_value
    '%s = %s' % (option.name, fmt_value(value, desc=option))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/snap/pbtk/34/lib/python3.12/site-packages/pbtk/utils/descpb_to_proto.py", line 137, in fmt_value
    val = desc.enum_type.values_by_number[val].name
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
TypeError: unhashable type: 'google._upb._message.RepeatedScalarContainer'
```
